<div id="download" class="indent_without_columns">
<a name="download"></a>
<h1>Download</h1>

<p>The latest version of Trizbort is version 1.2.1 You can <a href="history.html">view the full list of changes</a> here.</p>

<h2>Version 1.2.1 for Windows</h2>

<table><tr><td>
<a href="Trizbort121.zip"><img src="zip.png" alt="Zip File"></a>
</td></tr><tr><td>
<a href="Trizbort121.zip">Trizbort v1.2.1 Zip File (328k)</a>
</td></tr></table>

<p>Trizbort requires the <a href="http://www.microsoft.com/downloads/details.aspx?FamilyID=0856eacb-4362-4b0d-8edd-aab15c5e04f5">.NET Framework version 2</a> or higher to run. If you have a recent version of Windows you likely have this already.</p>

<p>If you have a previous version of Trizbort installed, you should uninstall it prior to installing the new version.</p>

<h2>Previous Version: 1.2 for Windows</h2>

<table><tr><td>
<a href="TrizbortSetup120.exe"><img src="setup.png" alt="Setup"></a>
</td><td>
<a href="Trizbort120.zip"><img src="zip.png" alt="Zip File"></a>
</td></tr><tr><td>
<a href="TrizbortSetup120.exe">Trizbort v1.2 Installer (560k)</a>
</td><td>
<a href="Trizbort120.zip">Trizbort v1.2 Zip File (290k)</a>
</td></tr></table>

<p>Trizbort requires the <a href="http://www.microsoft.com/downloads/details.aspx?FamilyID=0856eacb-4362-4b0d-8edd-aab15c5e04f5">.NET Framework version 2</a> or higher to run. If you have a recent version of Windows you likely have this already.</p>

<p>If you have a previous version of Trizbort installed, you should uninstall it prior to installing the new version.</p>

<h2>Mac, Linux</h2>

<p>Unfortunately there is no Mac or Linux version of Trizbort at this time.</p>

<p>Some users have reported success running Trizbort under Wine using Mono.</p>

<h1>License</h1>

<p>Trizbort v1.2.1 is licensed under the <a href="https://github.com/genstein/trizbort/blob/master/LICENSE.txt">MIT License</a>.</p>

<p>Trizbort v1.2 and earlier are licensed under the <a href="http://creativecommons.org/licenses/by-nc-nd/2.0/uk/">Creative Commons Attribution-Non-Commercial-No Derivative Works 2.0 UK: England & Wales Licence</a>.</p>

<p>Trizbort makes use of <a href="http://www.pdfsharp.com">PDFsharp</a>, copyright (c) 2005-2007 empira Software GmbH, Cologne (Germany).</p>
</div> <!-- download -->
