<div id="feedback" class="indent_without_columns">
<a name="feedback"></a>
<h1>Contact</h1>

<p>Trizbort was created by Genstein in 2010 and 2011. Not a lot happened to it in 2012, but purportedly there are plenty of people using it right now.</p>

<h2>Feedback</h2>

<p>Flames, questions, stylish maps for this page, and anything else vaguely related to Trizbort can be sent to <a href="http://www.google.com/recaptcha/mailhide/d?k=01XQEnuJLPVEm7kDYSz_h_oQ==&amp;c=X3YXHF2CPVgt4IphTyRKsxArd-_4j9P_38kR9NBciwc=">this address</a>.</p>

<h2>Donations</h2>

<p>Now that Trizbort is open source I am no longer accepting donations via this website. Please give to a charity of your choice instead. Thank you.</p>

</div> <!-- feedback -->
