</div> <!-- bodycontainer -->
<div class="domainbar bottomdomainbar">
<div class="domainbar_indent">
<!-- keep this on one line, since the bar is fixed height -->
<span class="siteheading">&copy;&nbsp;2010-2015</span><div style="float: right; margin-top: 8px; margin-right: 10px;"><a href="http://validator.w3.org/check?uri=referer"><img src="http://www.w3.org/Icons/valid-html401" alt="Valid HTML 4.01 Strict" style="border:0;width:88px;height:31px"></a><a href="http://jigsaw.w3.org/css-validator/check/referer"><img style="border:0;width:88px;height:31px" src="http://jigsaw.w3.org/css-validator/images/vcss" alt="Valid CSS"></a></div>
</div>
</div>
</body>
</html>
