</head>
<body>
<div class="domainbar topdomainbar">
<div class="domainbar_indent">
&nbsp;
</div>
</div>
<div class="areabar">
<div class="areabar_indent">
<span class="areabar_superheading">Trizbort</span><span class="areabar_quote">&nbsp;&nbsp;&there4;</span><br>
<span class="areabar_majorheading">The Interactive Fiction Mapper</span><br>
<span class="areabar_quote"><i>trizbort <strong>n.</strong></i> incantation causing a spatial shift. Easily confused with <i>satchmoz</i>, an incantation causing a shift in space.</span>
</div>
</div>
<div class="buttonbar" id="navigation">
<div class="buttonbar_indent">
<a class="button" href="javascript:switchTo('overview')">&gt; Restart</a>
<a class="button" href="javascript:switchTo('media')">&gt; Examine Trizbort</a>
<a class="button" href="javascript:switchTo('download')">&gt; Get Trizbort</a>
<a class="button" href="javascript:switchTo('help')">&gt; Help</a>
<a class="button" href="javascript:switchTo('feedback')">&gt; Hello, Sailor</a>
</div>
</div>
<div class="bodycontainer">
