<div id="media" class="indent_without_columns">
<a name="media"></a>
<h1>Screenshots</h1>

<p>Click any thumbnail to view a larger image.</p>

<p>
<a href="shot1.png"><img src="shot1_thumb.png" alt="Screenshot"></a>
<a href="shot2.png"><img src="shot2_thumb.png" alt="Screenshot"></a>
<a href="shot3.png"><img src="shot3_thumb.png" alt="Screenshot"></a>
<a href="shot4.png"><img src="shot4_thumb.png" alt="Screenshot"></a>
</p>

<h1>Sample Maps</h1>

<p><strong>Spoiler Alert: </strong>Viewing these samples may spoil your enjoyment of the games involved. There are a lot of clues in the maps, to say the least.</p>

<ul>
<li>Complete map of Planetfall <a href="Planetfall.trizbort">(Trizbort, 28k)</a> <a href="planetfall_map.pdf">(PDF, 25k)</a> <a href="planetfall_map.png">(PNG, 1.3mb)</a>
</ul>
</div> <!-- media -->
