<div id="overview">
<a name="overview"></a>
<div class="colmask doublepage">
<div class="colleft">
<div class="col1">
<div class="indent_column">
<h1>Overview</h1>

<p>Trizbort is a simple tool which can be used to create maps for <a href="http://en.wikipedia.org/wiki/Interactive_fiction">interactive fiction</a>.</p>

<p>Over the years a number of styles have evolved for interactive fiction mapping. Trizbort focuses on creating maps in only one of these styles, as popularised by <a href="http://en.wikipedia.org/wiki/Infocom">Infocom</a>: labelled boxes for rooms, with lines connecting them.</p>

<p>Whether you're playing or writing interactive fiction, mapping can be invaluable. Trizbort is just one of <a href="http://www.ifarchive.org/indexes/if-archiveXmapping-tools.html">many mapping tools</a> for interactive fiction: I hope you find it useful, but you may want to check out the others too.</p>

<p>Features include:</p>

<ul>
<li>A simple point and click interface to create rooms, resize them and connect them together;
<li>Smart* lines which snap to the cardinal** points on room edges;
<li>Rooms can be marked as dark or light; dark rooms on the map have shaded corners;
<li>A list of objects per room, which can be "docked" to any room edge or placed inside the room;
<li>Customisable colours, fonts and drawing styles;
<li>A "hand-drawn" line style for that back-of-an-envelope feel;
<li>Title, description and author text which will be saved with the map;
<li>Export to PDF files and PNG images for posterity or printing;
<li>Multiple selection;
<li>Single keypress keyboard shortcuts;
<li>An XML file format in case other tools wish to generate or read Trizbort maps.
</ul>

<p>* <span class="footnote">Not that smart.</span><br>

** <span class="footnote">More or less cardinal. In fact Trizbort adds some decidedly non-cardinal points to make things easier.</span></p>
</div> <!-- indent_column -->
</div> <!-- col1 -->
<div class="col2">
<div class="indent_column">
<h1>Latest News</h1>

<h2>January 18th, 2015</h2>

<p>Trizbort's documentation is now also open source, under the same license, at <a href="https://github.com/genstein/trizbort/tree/master/Docs">https://github.com/genstein/trizbort/tree/master/Docs</a>.</p>

<p>Some people are working on forks of Trizbort: you may find them via <a href="https://github.com/genstein/trizbort/network">GitHub</a> or search the <a href="http://intfiction.org/forum">Interactive Fiction Community Forum</a>.

<h2>March 16th, 2013</h2>

<p>Trizbort is now open source! The latest version is now 1.2.1 which is largely identical to 1.2 except for About box changes and the lack of a Donate window (which didn't seem quite right in light of the change, as that was donating to me personally). It is now licensed under the MIT License. You can now find the source code at <a href="http://github.com/genstein/trizbort">http://github.com/genstein/trizbort</a>.</p>

<h2>March 13th, 2011</h2>

<p>Version 1.2 has been released. This is a major update to Trizbort. The <a href="history.html">full release notes</a>
are online, but most significantly:</p>
<ul>
<li><a href="/help/">A complete user guide</a> to Trizbort is now online.
<li>Trizbort now supports automapping from game transcripts.
<li>You can now export your maps to Inform 7, TADS and Inform 6.
<li>No more modes! You can now draw connections whenever nothing is selected, and you can always select things.
<li>A "minimap" gives you an overview of your whole map, and you can click and drag it to scroll around.
<li>Scroll bars finally make an appearance on the canvas, and the cursor keys now work too.
<li>The File menu sports a list of recently used maps, and your most recent save/export folders are remembered.
</ul>

<h2>February 18th, 2011</h2>

<p>Version 1.1 has been released. The <a href="history.html">full release notes</a>
are online, but most significantly:</p>
<ul>
<li>Trizbort now supports selecting multiple rooms and connections at the same time and many operations now work on such selections.
<li>New keyboard shortcuts and menu options make it easier to change connection (line) styles.
<li>The installer also adds a "Trizbort Map File" template to Windows Explorer so you can create new maps and then double click them to open Trizbort.
<li>Drawing optimizations should also mean that large maps will display a little faster.
</ul>

<h2>October 12th, 2010</h2>

<p>Version 1.0.1 has been released, fixing a bug reported by several people which could cause Trizbort to use 100% CPU time even when idle. Trizbort tries quite enthusiastically to update its menu and toolbars to make sure everything is checked or greyed out as appropriate, and it was getting a little over zealous to say the least.</p>
</div> <!-- indent_column -->
</div> <!-- col2 -->
</div> <!-- colleft -->
</div> <!-- colmask doublepage -->
</div> <!-- overview -->
